version: '3.9'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tracker
    healthcheck:
      test: "pg_isready -U postgres -d tracker"
      interval: 5s
      timeout: 5s
      retries: 3
  app:
    build:
      context: .
      dockerfile: CompetencyTracker/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=password;Database=tracker
      - UseSwagger=true
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs