version: '3.9'

volumes:
  postgres-data:


services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres -d database"
      interval: 5s
      timeout: 5s
      retries: 3
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=password;Database=database
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs